.TH "src/CEEnumerator.h" 3 "Thu Apr 28 2011" "Version 0.0.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CEEnumerator.h \- 
.PP
Here defined ChEngn::Enumetaror class.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <CETable.h>\fP
.br
\fC#include <CEPiece.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChEngn::Enumerator\fP"
.br
.RI "\fIEnumerate possibile moves. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBChEngn\fP"
.br
.PP

.RI "\fIContains all typedefs, constants, classes defined in. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBChEngn::EnumerationSide\fP { \fBChEngn::UndefinedSide\fP =  0, \fBChEngn::WhiteSide\fP, \fBChEngn::BlackSide\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Here defined ChEngn::Enumetaror class. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
