.TH "src/CETable.h" 3 "Thu Dec 29 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CETable.h \- 
.PP
\fBChEngn::default_table_height\fP, \fBChEngn::default_table_width\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CEPiece.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChEngn::Table\fP"
.br
.RI "\fIChess board. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBChEngn\fP"
.br
.PP

.RI "\fIContains all typedefs, constants, classes defined in. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBChEngn::default_table_height\fP = 8"
.br
.RI "\fIStandart table height. \fP"
.ti -1c
.RI "const unsigned int \fBChEngn::default_table_width\fP = 8"
.br
.RI "\fIStandart table width. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBChEngn::default_table_height\fP, \fBChEngn::default_table_width\fP. 

Here defined \fBChEngn::Table\fP, ChEngn::table_size, 
.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
