.TH "src/CEUtils.h" 3 "Sat Apr 30 2011" "Version 0.0.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/CEUtils.h \- 
.PP
Here are defined ChEngn::Exception class.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBChEngn\fP"
.br
.PP

.RI "\fIContains all typedefs, constants, classes defined in. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBChEngn::itostr\fP (int num)"
.br
.RI "\fIConverts given number to std::string. \fP"
.ti -1c
.RI "const char * \fBChEngn::itoa\fP (int num)"
.br
.RI "\fIConverts given number to std::string. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Here are defined ChEngn::Exception class. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
