.TH "ChEngn::BadMove" 3 "Thu Apr 28 2011" "Version 0.0.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChEngn::BadMove \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBadMove\fP (pgn::Ply p, int moveNum=0)  throw ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP ()  throw ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
