.TH "ChEngn::PawnMove" 3 "Thu Dec 29 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChEngn::PawnMove \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBChEngn::Move\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPawnMove\fP (const \fBpgn::Ply\fP *ply, const bool isWhite)"
.br
.ti -1c
.RI "virtual bool \fBmake\fP (const \fBTable\fP *table) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
