.TH "ErrorMessages" 3 "Tue Apr 12 2011" "Version 0.0.1a" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorMessages \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
contains all standart error's messages 
.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
