.TH "ErrorCodes" 3 "Tue Apr 12 2011" "Version 0.0.1a" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorCodes \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
contains definition of all error codes 
.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
