.TH "pgn::invalid_castle_string" 3 "Tue May 31 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::invalid_castle_string \- 
.PP
Throws when castle in pgnfile is incorrect format.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PGNException.h>\fP
.PP
Inherits \fBpgn::parse_exception\fP.
.SH "Detailed Description"
.PP 
Throws when castle in pgnfile is incorrect format. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
