.TH "pgn::bad_pgn_file" 3 "Wed Jun 1 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::bad_pgn_file \- 
.PP
Throws when file in incorrect/invalid.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PGNException.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbad_pgn_file\fP (const std::string message)  throw ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Throws when file in incorrect/invalid. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
