.TH "pgn::unsupported_variations" 3 "Wed Jun 1 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::unsupported_variations \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBpgn::parse_exception\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
