.TH "pgn::invalid_tag" 3 "Wed Jun 1 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::invalid_tag \- 
.PP
Throws when file contains tag with wrong format.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PGNException.h>\fP
.PP
Inherits \fBpgn::parse_exception\fP.
.SH "Detailed Description"
.PP 
Throws when file contains tag with wrong format. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
