.TH "pgn::invalid_ply_text" 3 "Sun Jun 5 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::invalid_ply_text \- 
.PP
Throws when ply is in incorrect format.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PGNException.h>\fP
.PP
Inherits \fBpgn::parse_exception\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinvalid_ply_text\fP (const std::string &ply)  throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Throws when ply is in incorrect format. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
