.TH "pgn::Square" 3 "Tue May 31 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::Square \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSquare\fP (char col, char row)"
.br
.ti -1c
.RI "\fBSquare\fP (const \fBSquare\fP &src)"
.br
.ti -1c
.RI "\fBSquare\fP & \fBoperator=\fP (const \fBSquare\fP &src)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSquare\fP &src) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSquare\fP &src) const "
.br
.ti -1c
.RI "char \fBcol\fP () const "
.br
.ti -1c
.RI "char \fBrow\fP () const "
.br
.ti -1c
.RI "int \fBcolIndex\fP () const "
.br
.ti -1c
.RI "int \fBrowIndex\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
