.TH "pgn::MoveList::iterator" 3 "Thu Dec 29 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pgn::MoveList::iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (const \fBMoveList\fP &ml)"
.br
.ti -1c
.RI "\fBiterator\fP (const \fBMoveList\fP &ml, int)"
.br
.ti -1c
.RI "\fBiterator\fP (const \fBiterator\fP &)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator=\fP (const \fBiterator\fP &)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBMove\fP * \fBoperator->\fP () const "
.br
.ti -1c
.RI "const \fBMove\fP & \fBoperator*\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
