.TH "src/libpgnm/src/PGNCommentText.h" 3 "Thu Dec 29 2011" "Version 0.2.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libpgnm/src/PGNCommentText.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpgn::CommentText\fP"
.br
.RI "\fIProvides comment to move. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBpgn\fP"
.br
.PP

.RI "\fIglobal namespace for libpgnm \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for libchessengine from the source code.
