.TH "README" 3 "Wed Apr 13 2011" "Version 0.0.1" "libchessengine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
README \- .SH "About"
.PP
libchessengine - Parse PGN files, make moves from an game in input PGN file, print game, move, table to stream like std::ostream ( for example std::cout ) Uses modified pgnlib for parse PGN files
.SH "Library"
.PP
Compile, decompile chess games from/to *.pgn files. \fBhttp:\fP//en.wikipedia.com/PGN_Notation Uses GNU GPL library. Original source: http://sourceforge.net/projects/pgnlib
.SH "Installation Chess engine"
.PP
\fBNote:\fP
.RS 4
Install libpgn first (\fBlibpgn Installation\fP), then instal libchessengine make 
.RE
.PP
sudo make install 
.SS "libpgn Installation"
./configure make sudo make install 
.SH "Using"
.PP
First \fBInstallation Chess engine\fP This library can be build as static library and/or shared object 
.PP
\fBSee also:\fP
.RS 4
examples 
.RE
.PP

